### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by robertodevet** [OttoDIY/MATRIX#1]
Hello , i like this project and would like to build one.
The fact that this one has an lipo instead of the batteries and an touchsensor appeals to me very much.
But i would like to know wich lipo and charge/protect unit you use for this project ,i can't see any info on that.
Also an schematic would be nice , so i know on which input/output i can connect everything.
I hope you can provide me with some links.

**Comment by cparrapa** [comment]
For LiPO there are many options @dlevstek or @jarsoftelectrical can tell you more details

**Comment by dlevstek** [comment]
I'm on vacation now and still waiting for some parts to test. I'll try to draw some schematic when I get back next week.

**Comment by robertodevet** [comment]
Thanks both for the reply.
I have got the normal Otto to work , but want to extend with the touch sensor.
Ordered the parts and the lipo charge/protect boost converter .
About the lipo and connecting it i am sure i can manage , but the touch sensor is new to me.
Appreciate the help with that , i think it's interesting in other arduino projects as well.
@dlevstek  , enjoy your vacation @

**Comment by dlevstek** [comment]
Thanks. Touch sensor is no problem, you connect + to +, - to - and signal to button input. Signal goes  high when sensor reacts and that's the same behaviour like when using the button.

**Comment by robertodevet** [comment]
Wow  ,that pretty simple , so i don't need to change the arduino sketch.

**Comment by dlevstek** [comment]
No, v3 sketch is already modified for touch sensor on pin 6.

**Comment by cparrapa** [comment]
connections updated
