### ISSUE TITLE
Otto.cpp Otto::bendTones bug

### ISSUE THREAD

**Issue by markalunwinn** [OttoDIY/MATRIX#2]
The internal loop variable i should be float not int. Otherwise if the increment is too small, it will loop forever. It took me a few hours to find this issue.

**Comment by cparrapa** [comment]
cool can you pull a request? an we will change that

**Comment by markalunwinn** [comment]
Sorry, I'm new to github so don't know how to do that - sorry for the noob question

**Comment by cparrapa** [comment]
i see no problem you can share the code in an email or something 
thanks!
