### ISSUE TITLE
Matrix_Hands version

### ISSUE THREAD

**Issue by Pranta-UAP** [OttoDIY/MATRIX#4]
Hi,
I'm Pranta from Bangladesh.
Would you please guide me with a link/video/repository(with design file,codes,app) to design and make Otto Matrix_Hand Version that has functions like
1. Bluetooth Control
2. Matrix Mouth(with emotions) and hands
3. Cathode light nose
4. Dance
5. Walk and avoid

I searched for step by step process to build it. But not found.
I found other Otto's version **with design files, codes and android app with easy steps**. But i did not find Matrix_Hands version.

**3D printing is rare in my country**. I want to modify Otto later again. That's why I'm searching for the advance design.

**If it is possible without Nano I/O shield,  if it can be build with nano+breadboard it will be better for me. Yet I/O shield is not available in the city.**

Please suggest me. Waiting for your response.

**Comment by cparrapa** [comment]
Hi Panda
this is a work in progress that is why there is not a guide
we would like people like you to helps us finish this repository clear and easy to understand

you can use breadboard or get one of our kits directly ship to your country
Welcome to the community!

**Comment by cparrapa** [comment]
Hi Panda
the APP with songs that is something i would like to have too, we need some help there so is more like an idea rather than an issue
thanks!
