### ISSUE TITLE
Error compiled

### ISSUE THREAD

**Issue by pepegragera** [OttoDIY/MATRIX#5]
I'm trying to compile the plus version and the matrix and I always have the same error:

Arduino:1.8.5 (Windows 10), Tarjeta:"Arduino Nano, ATmega328P (Old Bootloader)"

C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino:74:0: warning: "BAT_MAX" redefined

 #define BAT_MAX  4.8 //use this

 ^

In file included from C:\Program Files (x86)\Arduino\libraries\Otto/Otto.h:10:0,

                 from C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino:39:

C:\Program Files (x86)\Arduino\libraries\BatReader/BatReader.h:22:0: note: this is the location of the previous definition

 #define BAT_MAX 4.2

 ^

C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino:75:0: warning: "BAT_MIN" redefined

 #define BAT_MIN 3.6  //and this for NiMh battery

 ^

In file included from C:\Program Files (x86)\Arduino\libraries\Otto/Otto.h:10:0,

                 from C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino:39:

C:\Program Files (x86)\Arduino\libraries\BatReader/BatReader.h:23:0: note: this is the location of the previous definition

 #define BAT_MIN 3.25

 ^

C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino: In function 'void loop()':

Otto_v3:534: error: 'ledR' was not declared in this scope

               digitalWrite(ledR, LOW);

                            ^

Otto_v3:535: error: 'ledG' was not declared in this scope

               digitalWrite(ledG, LOW);

                            ^

Otto_v3:536: error: 'ledB' was not declared in this scope

               digitalWrite(ledB, LOW);

                            ^

C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino: In function 'void OttoSleeping_withInterrupts()':

Otto_v3:1408: error: 'ledR' was not declared in this scope

     digitalWrite(ledR, HIGH);

                  ^

Otto_v3:1409: error: 'ledG' was not declared in this scope

     digitalWrite(ledG, HIGH);

                  ^

Otto_v3:1410: error: 'ledB' was not declared in this scope

     digitalWrite(ledB, HIGH);

                  ^

C:\Users\Pepe Gragera\Downloads\MATRIX-master\MATRIX-master\Otto_v3\Otto_v3.ino: In function 'void OttoArmingAlarmSystem()':

Otto_v3:1460: error: 'ledR' was not declared in this scope

     digitalWrite(ledR, LOW);

                  ^

Otto_v3:1461: error: 'ledG' was not declared in this scope

     digitalWrite(ledG, HIGH);

                  ^

Otto_v3:1462: error: 'ledB' was not declared in this scope

     digitalWrite(ledB, LOW);

                  ^

exit status 1
'ledR' was not declared in this scope

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by dlevstek** [comment]
Did you try using modified otto.h and otto.cpp libraries? Try libraries and sketch from here: https://github.com/dlevstek/Otto

**Comment by pepegragera** [comment]
Same problem:
In V2
Otto_v2:1219: error: 'ledR' was not declared in this scope

In V3
Otto_v3:534: error: 'ledR' was not declared in this scope

**Comment by cparrapa** [comment]
try now with new libraries
